paths:
  bower:
    main: "./bower_components"
    angular: "./bower_components/angular/angular.js"
    angularRoute: "./bower_components/angular-route/angular-route.js"
    angularMocks: "./bower_components/angular-mocks/angular-mocks.js"

  coffee:
    admin:
      main: "./src/app/admin/*.coffee"
      app: "./src/app/admin/app/*.coffee"
    client:
      main: "./src/app/client/*.coffee"
      app: "./src/app/client/app/*.coffee"
    shared:
      main: "./src/app/shared/*.coffee"
      app: "./src/app/shared/app/*.coffee"

  templates:
    index: "./src/app/index.html"
    admin: "./src/app/admin/partials/**"
    client: "./src/app/client/partials/**"

  assets:
    fonts: "./src/assets/fonts/**"
    images: "./src/assets/images/**"
    styles: "./src/assets/styles/styles.styl"

  target:
    main: "./target"
    scriptsDest:
      all: "./target/*.js"
      admin: "./target/admin-app.js"
      client: "./target/client-app.js"
      lib: "./target/lib.js"
      templates:
        admin: "./target/admin-templates.js"
        client: "./target/client-templates.js"
    scripts:
      admin: "admin-app.js"
      client: "client-app.js"
      lib: "lib.js"
      templates:
        admin: "admin-templates.js"
        client: "client-templates.js"
    indexDest: "./target/index.html"
    assets:
      fonts: "./target/fonts"
      images:
        all: "./target/images/*.*"
        dest: "./target/images"
      styles: "./target/styles.css"

  test:
    admin: './test/admin/*.spec.coffee'
    client: './test/client/*.spec.coffee'